version: '3.1'

services: 

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports: 
      - '4566:4566'
      - '4571:4571'
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
